### ISSUE TITLE
Shears suddenly fill with energy when held.

### ISSUE THREAD

**Issue by brisingraerowing** [CyclopsMC/EnergeticSheep#12]
#### Issue type:

_Only keep the issue types that are applicable._

- :bug: Bug

____
#### Short description:
When holding a pair of energetic shears, they fill with energy.

#### Expected behaviour:
Shears to stay empty.

#### Actual behaviour:
Shears fill with energy.

#### Steps to reproduce the problem:

1. Get some energetic shears
2. Hold them (main hand)
3. ???
4. Free energy!

____
#### Versions:

_Exact versions of the following mods, not just *latest*._

- This mod: 1.12.2-1.1.0
- CyclopsCore: 1.12.2-0.11.0
- Minecraft: 1.12.2
- Forge: 2575 (newer versions crash a lot of mods due to model loader changes)

#### Log file:
No crash. I'll upload the game output and fml logs if you want.

**Comment by rubensworks** [comment]
Any more information you can give me? You're probably using another mod that fills held items with energy.

Can you check if this also occurs in an environment with just this mod and its dependencies installed?

**Comment by brisingraerowing** [comment]
Yes. I forgot I had a draconic evolution capacitor in my inventory. Doh.
