### ISSUE TITLE
Orange Energetic Wool does not add energy

### ISSUE THREAD

**Issue by TheSaltyPug** [CyclopsMC/EnergeticSheep#16]
#### Issue type:

- :bug: Bug

____

#### Short description:

Using the orange energetic wool on an energy container does not seem to work.

#### Steps to reproduce the problem:

1. I sheared the orange energetic sheep
2. Right click on an EnderIO capacitor bank OR a thermal expansion energy cell

#### Expected behaviour:

Energy from the wool should go into the block, however it just opens the GUI for the block.

____

#### Versions:

- This mod: 1.12.2-1.1.2 (latest release as of June 2, '18)
- Minecraft: 1.12.2
- Forge: 14.23.4.2705

#### Log file:

Not a crash, but if you need me to dig up a log for it I can.

Thanks boss

**Comment by rubensworks** [comment]
Works just fine for me on ID batteries. It's possible that other energy blocks block interaction, which would require you to insert the energy through some other method. (Both EiO and TE provide methods for that AFAIK)
