### ISSUE TITLE
Energetic Shear going negative on energy infinitely

### ISSUE THREAD

**Issue by corey8084** [CyclopsMC/EnergeticSheep#17]
#### Issue type: Bug

- :bug: Bug

____

#### Short description:

Playing in the stoneblock mod pack, I was using the energetic shear to shear botanical plants. Flux Network and Ender IO were handling my wireless charging and I was using the Draconic Evolution Draconic Flux Capacitor as my inventory battery. I also had a full tier 4 energy core from Draconic Evolution and a production of 65k RF/t from an Extreme Reactor reactor. While cutting plants, I noticed the shears were out of power, then I noticed my capacitor was empty, and my entire energy core was completely drained, further investigation found that the shears had negative some huge number rf. I didn't even put them away in my refined storage system, I immediately deleted them. 

#### Steps to reproduce the problem:

1. I don't know which mod interaction caused this as you can see I have a few working together right now. I can do more research if need be. 
My best guess for recreating this is that I was shearing those plants pretty rapid fire like. I imagine that at some point an int wasn't handled properly, it got inverted and tried to charge, but because the number was negative, it had no ceiling (negative infinity < energy cap after all)

#### Expected behaviour:

I expected that the shears would remain fully charged, or at the very least not suck energy into negative infinity.

____

#### Versions:

- This mod: 1.1.2
- Minecraft: 1.12.2
- Forge: 14.23.5.2768 (I think you're referring to Minecraft Forge)

#### Log file:

Log files and additional information can be provided at dev's request.

**Comment by rubensworks** [comment]
A lot of different things could be going wrong indeed.

* shearing
* EIO wireless charing
* DE flux capacitor
* ...

If you manage to reproduce this consistently, be sure to let me know.

**Comment by corey8084** [comment]
I'll make a copy of my world and go creative to see if I can recreate that for you.

**Comment by corey8084** [comment]
Alright, after a good bit of testing I've been able to recreate the problem.
Setup: 
Create 2 flux network controllers. 
Create a DE energy core (I tested with a tier 4)
Place a Mekanism creative energy cube
Attach flux plug to energy cube turn off transfer limit and set to network 1
Attach flux point to input energy pylon for energy core (should instantly fill up) turn off transfer limit, set to network 1
Attach flux plug to output energy pylon for energy core turn off transfer limit, set to network 2
On first network controller, set it to network 1
On second controller, set it to network 2
Put energetic shear in inventory (any slot works)
On second controller, turn on wireless charging and ensure all charging options are enabled. (only the one that includes the inventory slot that has the shear in it, but select all to be safe)
Once this is done, you should now see the shear rapidly changing from full energy to negative and back.

I did try this with other setups including having no energy buffer (like the energy core) I also tried it with using vibrant capacitors from Ender IO but that only caused the shear to go negative and slowly start recharging, it was not as rapid as with the DE energy core. I wonder if this is a case of the flux network overpowering the shear and causing this problem? I hope this helps. I did try to go through the logs to see if there was an exception getting swallowed, but saw none.

Let me know if you need any more information.

**Comment by rubensworks** [comment]
Ok, so the shears seem to allow insertion even when full.

Thanks for the info! Will look into it soon.
