### ISSUE TITLE
Electric Sheep spawn in biomes that normal sheep do not

### ISSUE THREAD

**Issue by LordEpos** [CyclopsMC/EnergeticSheep#22]
Electric Sheep seem to (in 1.12.2-latest) appear in deserts, while vanilla sheep don't. Been working on a pack where the player spends a lot of time in the desert, and ended up removing this for that reason.

**Comment by rubensworks** [comment]
So I assume this is a feature request to configure the list of biomes in which sheep can spawn.

**Comment by rubensworks** [comment]
This can be done using biome modifiers now.
