### ISSUE TITLE
Energetic Sheep Spawning Rules

### ISSUE THREAD

**Issue by Kriscj** [CyclopsMC/EnergeticSheep#23]
#### Issue type:

- :heavy_plus_sign: Feature request

____

#### Short description:

This mod is included in the Janky Skyblock modpack on Twitch.  While playing that, I have noticed that the Energetic Sheep are spawning on blocks that no animals should spawn upon, such as cobble, top-half slabs, wood, etc, and within 24 blocks of world spawn.  Regardless of biome, should they at least not follow the same basic rules as other passive land mobs?  IE, on grass only, in compatible (or perhaps config-controlled) biomes, and only outside the world spawn minimum?  

It's a real pain to be building some new wing on my skyblock and come back to find my central hub overrun with fast-moving sheep that have a real chance of knocking me off.  :)  (I know, I know, build a sissy bar... )

So, my request is for exactly that: energetic sheep, when allowed by config to spawn without lightning, should be allowed to spawn only on blocks other passive land mobs would.

Thanks!

**Comment by rubensworks** [comment]
This sounds like a pack-specific issue. This mod only spawns sheep when the chunks are first generated. But what you are experiencing is that sheep are re-spawning when you leave and re-enter chunks. This sounds like another mod doing this, so I would suggest you take this up with the pack author.
