### ISSUE TITLE
all sheeps spawned are energetic and spawn in middle of oceans

### ISSUE THREAD

**Issue by babacon88** [CyclopsMC/EnergeticSheep#29]
#### Issue type:

- :bug: Bug 

____

#### Short description:

____

#### Versions:

- This mod: EnergeticSheep-1.19-1.1.9.jar
- Minecraft: 1.19 forge 41.1.0
- Forge: forge 41.1.0

#### Log file:
How do I get this in middle of the game?, I only know how to collect crash logs

**Comment by rubensworks** [comment]
@babacon88 Your issue appears to be not following one of the allowed issue templates, which breaks our automation tools. Please update your issue to the proper template.
