### ISSUE TITLE
Crash with Tinted, Request for Support

### ISSUE THREAD

**Issue by ThugPug43** [CyclopsMC/EnergeticSheep#30]
#### Issue type:

- :bug: Bug

____

#### Short description:

EnergeticSheep crashes when trying to run with Tinted.

#### Steps to reproduce the problem:

1. Install EnergeticSheep, Cyclops Core, and Tinted for 1.19.2. The versions I used are below. It may crash on other versions of the mods as well, I have not tested.
2.) Launch the game
3.) Crash

#### Expected behaviour:

I expected the mod to run without support for the Tinted unique dyes. I was hopeful they might somehow be automatically supported or support was added and not documented. If they weren't supported I would have made a feature request for Tinted dyes and Energetic Sheep. I did not expect the crash and would still like Tinted support for the sheep. Let me know if I need to make a separate feature request for that.

____

#### Versions:

- EnergeticSheep: 1.19.2-1.17.0.jar
- Cyclops Core: 1.17.10
- Tinted: 1.10.1
- Minecraft: 1.19.2
- Forge: 43.1.7

#### Log file:

(https://pastebin.com/xdjdd7AG)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
AFAICS, this is a bug in the Tinted mod, so it might be better to report it to their issue tracker.

> java.lang.NullPointerException: Registry Object not present: tinted:coral_wool

But feel free to comment back here if the Tinted mod author thinks something needs to be changed on my end.
