### ISSUE TITLE
Mobspawner

### ISSUE THREAD

**Issue by caiofelipetz** [CyclopsMC/EnergeticSheep#32]
#### Issue type:

- :question: Question 

____

#### Question: 

Can anyone confirm if it was done on purpose that the sheep do not spawn by mobpspawners like the one in the Apotheosis mod?

**Comment by rubensworks** [comment]
Someone will answer your question soon. In the meantime, you might be able to get help more quickly on our [Discord server](https://discord.gg/9yDxubB).

**Comment by rubensworks** [comment]
I don't know the details of that mod, so I couldn't say tbh.
Best to ask it to the authors of that mod.
