### ISSUE TITLE
Energetic Sheep Crash - Accessing LegacyRandomSource from multiple threads

### ISSUE THREAD

**Issue by itsTort** [CyclopsMC/EnergeticSheep#33]
#### Issue type:

- :bug: Bug 

____

#### Steps to reproduce the problem:

1. ... UNK. Was flying in creative mode through a snowy biome when the crash occurred.

#### Expected behaviour:

____

#### Versions:

- This mod: EnergeticSheep-1.19.2-1.1.10
- Minecraft: 1.19.2 | 43.2.14
- Forge: yes

#### Log file:

[crash-2023-07-03_11.15.40-server.txt](https://github.com/CyclopsMC/EnergeticSheep/files/11945374/crash-2023-07-03_11.15.40-server.txt)

**Comment by rubensworks** [comment]
Thanks for reporting!
