### ISSUE TITLE
Energetic Sheep drop regular wool when sheared by the `shearable.shear` function

### ISSUE THREAD

**Issue by Meek97** [CyclopsMC/EnergeticSheep#34]
#### Issue type:

- :bug: Bug 

____

#### Short description:
The specific bug that I am experiencing:

> Energetic sheep drop regular sheep wool when sheared by the `Drum of the Gathering` from Botania.

However, I did a little research and I think that the underlying problem is more like:

> Energetic sheep drop regular sheep wool if they are sheared by an item or block that utilizes the `shearable.shear` function, like the Botania [`Drum of the Gathering`](https://github.com/VazkiiMods/Botania/blob/802c265c5c233a76d9bd9ccbf10db16fb560225c/Xplat/src/main/java/vazkii/botania/common/block/mana/DrumBlock.java#L136)

I'm guessing this is just due to the fact that the class extends `sheep` but probably doesn't overwrite the necessary properties for however the `shearable` class is handled

#### Steps to reproduce the problem:

1. Attempt to shear an Energetic Sheep with a Drum of the Gathering
2. Sheep get's sheared successfully, but only drops regular wool and retains it's charge.

#### Expected behaviour:

The sheep would drop energized wool and loose it's charge, just like it would when sheared by the player with regular shears
____

#### Versions:

- This mod: 1.1.10
- Minecraft: 1.19.2
- Forge: 43.2.11

**Comment by rubensworks** [comment]
Thanks for reporting!
