### ISSUE TITLE
Energetic Sheep cannot be killed w/ Apotheosis mod installed

### ISSUE THREAD

**Issue by sharkweekthings** [CyclopsMC/EnergeticSheep#35]
#### Issue type:

- :bug: Bug 

____

#### Steps to reproduce the problem:

1. Install EnergeticSheep-1.19.2-1.1.13 and Apotheosis-1.19.2-6.4.0.jar
2. spawn in Energetic Sheep
3. Attempt to hit/kill sheep
4. they can only be killed by indirect damage (explosions/etc)

#### Expected behaviour:

Sheep should be able to be killed through normal means via sword/axe/pickaxe/etc.

____

#### Versions:

- This mod: 
- Minecraft: 
- Forge: 1.19.2.43.43.3.2

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
This was fixed in 1.20, but apparently I forgot to backport it. Done in 684587acbbc1126520ee06c9e71d67e197e89cee
