### ISSUE TITLE
Optional Config To Disable Energetic Sheep Spawn

### ISSUE THREAD

**Issue by TheWireLord** [CyclopsMC/EnergeticSheep#36]
#### Issue type:

- :heavy_plus_sign: Feature request 

____

#### Short description:

It would be great to have an option in the Config File that allows you to enable or disable the natural spawning of Energetic Sheep in the world. Maybe adjust the spawn rate too?

This would instead require the player to create a Lighting Rod or have a Trident with the Channeling Enchant to conduct the lighting to their sheep if they wanted to start an Energetic Sheep farm. Or of course just wait for it to happen naturally.

For now I've just created a Datapack that edits the `spawn_energetic_sheep_overworld.json` file to look like this:

```
{
  "replace": true,
  "type": ""
}
```

And I *think* this works to prevent them spawning for now. (Hard to confirm that something NEVER spawns in an infinite world lol)

Anyway, love your mods! They are some of the core mods that keep my server interesting. 

Thanks for all of your hard work!

**Comment by rubensworks** [comment]
Thanks for the suggestion!

**Comment by rubensworks** [comment]
The datapack approach is the correct way to do this indeed. It also allows you to modify the spawn rate and such.
Since datapacks are much more expressive than config files, this is the best way to handle such configurations.
