### ISSUE TITLE
[1.12.2] Sheep Spawns

### ISSUE THREAD

**Issue by BuilderDan** [CyclopsMC/EnergeticSheep#4]
Sheeps appeared to spawn at higher rates in cooler climates, not sure why it may have also been because of how open it was and how unlikely it was for other mobs to spawn. Nonetheless, after flying around they seem to spawn pretty frequently. Almost too frequently at times.

**Comment by rubensworks** [comment]
Do you see them spawning more frequently than other animals?

What biomes did it occur in specifically? Modded biomes?

**Comment by BuilderDan** [comment]
I'll have to do more testing, and yes I am using Biomes o' plenty.

**Comment by BuilderDan** [comment]
Tested it out a bit more, seems ok so far.

**Comment by rubensworks** [comment]
Ok, closing this issue in that case. Thanks for testing!
