### ISSUE TITLE
Crash with Terraqueous

### ISSUE THREAD

**Issue by brisingraerowing** [CyclopsMC/EnergeticSheep#6]
#### Issue type:

_Only keep the issue types that are applicable._

- :bug: Bug

____
#### Short description:
Crashes randomly with Terraqueous (likely on their end).

#### Expected behaviour:

Not to crash

#### Actual behaviour:

Random crash

#### Steps to reproduce the problem:

1. Run Terraqueous and Energetic Sheep together in a 1.12.2 instance
2. Try throwing wheat on the floor near an energetic sheep (it seems to be an issue with mobs eating from the floor)

____
#### Versions:

_Exact versions of the following mods, not just *latest*._

- This mod: 1.12.2-1.0.2
- CyclopsCore: 0.10.22
- Minecraft: 1.12.2
- Forge: 2537

#### Log file:
[Crash Log](https://gist.github.com/BrisingrAerowing/f0e09714761af558f3dd7752f89b3ec2)

**Comment by brisingraerowing** [comment]
A quick look at the code, and this seems to be the same as #3, some more null checks are needed wherever the energyStorage variable is accessed.

Although, with the variable being null like this, it may need to be initialized somewhere other than in the entity load method.

**Comment by rubensworks** [comment]
Thanks for reporting! `energyStorage` should be initialized when the sheep is spawned (or reloaded), so this should not be able to happen. Will look into it!
