### ISSUE TITLE
Change spawn rate

### ISSUE THREAD

**Issue by tali713** [CyclopsMC/EnergeticSheep#7]
#### Issue type:
- :heavy_plus_sign: Feature request
A configuration setting to change spawn rate or disable natural spawn would be nice.

**Comment by rubensworks** [comment]
Sure, why not.

**Comment by Ozzymud** [comment]
Yes please and thank you. I spawned when testing onto a small island, there were like 30 of these sheep there. Love the concept, but these need to be truly rare if they spawn at all naturally.
