### ISSUE TITLE
Sheep loose data when picked up by other mods

### ISSUE THREAD

**Issue by TheLimePixel** [CyclopsMC/EnergeticSheep#8]
#### Issue type:
- :bug: Bug

#### Short description:
 The current way that the Energetic Sheep switch from sheared to not sheared, by having an armor value being removed, doesn't work too well with mods that allow you to carry mobs (Carry On, Extra Utilities, Industrial Foregoing) as when the Energetic Sheep in placed on the ground, it always has wool, as by default it has an armor value.

#### Expected behaviour:
 The Energetic Sheep, when placed back on the ground are in the same state in which they were before being picked up (sheared or not).

#### Versions:
- This mod: 1.12.2-1.0.3
- CyclopsCore: 1.12.2-0.10.23
- Minecraft: 1.12.2
- Forge: 14.23.0.2552

**Comment by rubensworks** [comment]
Do you mean that ESheep *without energy* that are picked up through the mechanisms provided the the mods you mentioned cause them to instantly *regain* energy after being placed again?

If this is the case, this sounds like an issue with those mods not properly calling the NBT serialization methods of entities. Or doing some special-casing with instances of sheep, and not taking into account possible subclasses.

**Comment by TheLimePixel** [comment]
By the looks of it, yes. But if NBT is the issue, I don't understand why this issue would occur with some mods and not with others. For example: the variants of mobs Quark adds are always the same when the mob is placed (even thought it's the same entity), the Chickens from the Chickens mod always keep their stats, while the Googly Eyes from the Googly Eyes mod can be added to or removed from the mob when it's placed.

**Comment by rubensworks** [comment]
The problem was on my end. This issue even occurred when just restarting your game.
